### PR TITLE
Add a11y plugin

### LINKED ISSUE #13: Add JSX a11y plugin
https://github.com/evcohen/eslint-plugin-jsx-a11y

Would probably be considered a breaking change to this lib.

### PR DESCRIPTION
**Pull request by dpikt**
Resolves #13

### CODE REVIEW

**Comment by dpikt** [comment]
@chawes13 good call. Would you be willing to try out the recommended rules on Artlook?

**Comment by chawes13** [comment]
Yeah, definitely. Should I add the plugin there directly or should we merge this and not publicize it until after a few weeks of tinkering?

**Comment by dpikt** [comment]
I'd go for the former, less merging and versions to deal with 😁

**Comment by chawes13** [comment]
You got it!

**Comment by chawes13** [comment]
🙈 
image

**Comment by dpikt** [comment]
@chawes13 oof! were any of them auto-fixes? Did any seem extraneous or were they all legit?

**Comment by chawes13** [comment]
@dpikt unfortunately I haven't looked at fixing the issues yet since the map details page scope exploded. I'll probably have feedback to report in the next 2 weeks

**Comment by dpikt** [comment]
Sounds good, I'll add an assignment for the follow-up.

**Comment by chawes13** [comment]
Closing in favor of `v3` updates

**Pull request closed without merging**
